apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: troetbot
  name: troetbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: troetbot
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: troetbot
    spec:
      containers:
        - name: troetbot
          image: troetbot
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: troetbot-config
            - secretRef:
                name: troetbot-secrets
          startupProbe:
            httpGet:
              path: /q/health/started
              port: 8080
            periodSeconds: 1
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            periodSeconds: 2
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
      restartPolicy: Always
